name: Chinees Medisch Centrum Maastricht
favicon: null
layout_spectrum: 0.89537
typography_spectrum: 0.8362124697305262
title: Chinese Medical Center Maastricht
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aca100'
    - '#aa0000'
    - '#b15300'
    - '#131313'
    - '#ddc4a4'
  brandStrength: 0.5625
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
